<?php

/**
 * PluginsfMaraePostVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMaraePostVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMaraePostVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMaraePostVote');
    }
}