<?php

/**
 * PluginsfMaraeCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginsfMaraeCategory extends BasesfMaraeCategory
{
	public function getTree()
	{
		$o = Doctrine_Core::getTable('sfMaraeCategory')->getTree();
		$o->setBaseQuery($this->baseQuery());
		
		return $o;
	}
	
	public function baseQuery()
	{
		return Doctrine_Query::create()
			->select('c.name, c.description, c.slug')
			->from('sfMaraeCategory c')
			->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
	}
}
