<?php

/**
 * PluginsfMaraePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginsfMaraePost extends BasesfMaraePost
{
	private $o;
	
	public function getTree()
	{
		$this->o = Doctrine_Core::getTable('sfMaraePost')->getTree();
		$this->o->setBaseQuery($this->baseQuery());

		return $this->o;
	}
	
	public function getTreeObject()
	{
		$this->o = Doctrine_Core::getTable('sfMaraePost')->getTree();
		$this->o->setBaseQuery($this->baseQuery(true));
		
		return $this->o;
	}
	
	public function baseQuery($as_object = false)
	{
		$q = Doctrine_Query::create()
			->select('p.*, gu.username, pv.vote')
			->from('sfMaraePost p')
			->innerJoin('p.sfGuardUser gu')
			->leftJoin('p.sfMaraePostVote pv')
			->where('p.category_id = ?', $this->getCategoryId())
			->orderBy('p.rgt DESC');
			
		if (!$as_object)
		{
			$q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
		}
		
		return $q;
	}
	
	public function orderByCreatedAt($as_object = false)
	{
		$q = $this->baseQuery($as_object);
		$q->orderBy('p.created_at DESC');
		
		$this->o->setBaseQuery($q);
	}
	
	public function getMaxRoot()
	{
		$q = Doctrine_Query::create()
			->select('MAX(root_id) AS max_root_id')
			->from('sfMaraePost')
			->where('category_id = ?', $this->getCategoryId())
			->fetchOne(null, Doctrine_Core::HYDRATE_ARRAY);
			
		return $q['max_root_id'];
	}
	
	public static function getOpacity($rating)
	{
		return sprintf("%.2f", ((((pow($rating-1, 6)*-1)*0.4)+1)));
	}
	
	public static function getColor($rating)
	{
		return sprintf('#%1$xff%1$x', 255-(pow($rating, 3)*63));		
	}
}
