<?php

/**
 * PluginsfMaraePostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMaraePostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMaraePostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMaraePost');
    }
}
