<?php

/**
 * PluginsfMaraeCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMaraeCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMaraeCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMaraeCategory');
    }
}
