<?php

/**
 * PluginsfMaraePostVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginsfMaraePostVote extends BasesfMaraePostVote
{
	const
		VOTE_UP = 1,
		VOTE_DOWN = 2;
	
	public static function getAverageRating($postVote)
	{
		$total = $positive = 0;
		
		foreach ($postVote as $vote)
		{
			if (1 == $vote['vote'])
			{
				$positive++;
			}
			
			$total++;
		}
		
		return self::ciLowerBound($positive, $total);
	}
	
	public static function hasUserVoted($postVote, $userId, $direction = false)
	{
		foreach ($postVote as $vote)
		{
			if ((!$direction) || (self::VOTE_UP == $direction && $vote['vote'] == 1) || (self::VOTE_DOWN == $direction && $vote['vote'] == -1))
			{
				if ($userId == $vote['user_id'])
				{
					return true;
				}
			}
		}
		
		return false;
	}
	
	/*
	 * http://www.derivante.com/2009/09/01/php-content-rating-confidence/
	 */
	public static function pNormalDist($qn)
	{
		$b = array(1.570796288, 0.03706987906, -0.8364353589e-3, -0.2250947176e-3, 0.6841218299e-5, 0.5824238515e-5, -0.104527497e-5, 0.8360937017e-7, -0.3231081277e-8, 0.3657763036e-10, 0.6936233982e-12);
	
		if (0.0 > $qn || 1.0 < $qn)
		{
			return 0.0;
		}
		
		if (0.5 == $qn)
		{
			return 0.0;
		}
		
		$w1 = $qn;
		
		if ($qn > 0.5)
		{
			$w1 = 1.0 - $w1;
		}
		
		$w3 = -log(4.0 * $w1 * (1.0 - $w1));
		
		$w1 = $b[0];
		
		for ($i = 1; $i <= 10; $i++)
		{
			$w1 += $b[$i] * pow($w3, $i);
		}
		
		if (0.5 < $qn)
		{
			return sqrt($w1 * $w3);
		}
		
		return -sqrt($w1 * $w3);
	}
	
	public static function ciLowerBound($positive, $total, $power = 0.05)
	{
		if (0 == $total)
		{
			return 0.0;
		}
		
		$z = self::pNormalDist(1 - $power / 2);
		
		$p = 1.0 * $positive / $total;
		
		return ($p + $z * $z / (2 * $total) - $z * sqrt(($p * (1 - $p) + $z * $z / (4 * $total)) / $total)) / (1 + $z * $z / $total);
	}
}