forum:
  class:   sfDoctrineRouteCollection
  options: { model: sfMaraeCategory, module: sfMaraeCategory, prefix_path: /forums, actions: [list, show] }

forum_show_forum:
  url:     /forum/:slug.:sf_format
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraeCategory, action: show, sf_format: "html" }

post_vote_up:
  url:     /posts/:id/voteup
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: voteUp }

post_vote_down:
  url:     /posts/:id/votedown
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: voteDown }

post_search:
  url:     /forums/search/:slug
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: search, slug: "" }

post_new:
  url:     /posts/:id/new
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: new }
  requirements:
    sf_method: get

post_new_create:
  url:     /posts/:id/new
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: createNew }
  requirements:
    sf_method: post

post_reply:
  url:     /posts/:id/reply
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: reply }
  requirements:
    sf_method: get

post_reply_create:
  url:     /posts/reply
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: createReply }
  requirements:
    sf_method: post

post:
  class:   sfDoctrineRouteCollection
  options: { model: sfMaraePost, module: sfMaraePost, prefix_path: /posts, actions: [list, show, edit, update, delete] }

post_show_post:
  url:     /post/:id/:slug
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: show }

