forum:
  class:   sfDoctrineRouteCollection
  options: { model: sfMaraeCategory, module: sfMaraeCategory, prefix_path: /forum, actions: [list, show] }

forum_show_forum:
  url:     /forum/:slug
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraeCategory, action: show }

post_vote_up:
  url:     /post/:id/voteup
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: voteUp }

post_vote_down:
  url:     /post/:id/votedown
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: voteDown }

post_search:
  url:     /forum/search/:slug
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: search, slug: "" }

post_new:
  url:     /post/:id/new
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: new }
  requirements:
    sf_method: get

post_new_create:
  url:     /post/:id/new
  class:   sfDoctrineRoute
  options: { model: sfMaraeCategory, type: object }
  param:   { module: sfMaraePost, action: createNew }
  requirements:
    sf_method: post

post_reply:
  url:     /post/:id/reply
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: reply }
  requirements:
    sf_method: get

post_reply_create:
  url:     /post/reply
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: createReply }
  requirements:
    sf_method: post

post:
  class:   sfDoctrineRouteCollection
  options: { model: sfMaraePost, module: sfMaraePost, prefix_path: /post, actions: [list, show, edit, update, delete] }

post_show_post:
  url:     /post/:id/:replies
  class:   sfDoctrineRoute
  options: { model: sfMaraePost, type: object }
  param:   { module: sfMaraePost, action: show, replies: 0 }
  requirements:
    replies: \d+

